# Easy override for expression.ebnf

BIND_LEFT = '(' ;  BIND_RIGHT = ')' ;

TERNARY_CMP = '?' ;  TERNARY_SEP = ':' ;

INVOKE_LEFT = '(' ;  INVOKE_RIGHT = ')' ;  INVOKE_SEP = ',' ;

ATTR_ACCESS = '.' ;
INDEX_LEFT = '[' ;  INDEX_RIGHT = ']' ;

UPLUS = '+' ;  UMINUS = '-' ;  UBITNOT = '~'  ; ULOGNOT = '!' ;

OP_EXP  = '**' ;
OP_MOD  = '%'  ;
OP_DIV  = '/'  ;
OP_MULT = '*'  ;
OP_MMUL = '@'  ;
OP_ADD  = '+'  ;
OP_SUB  = '-'  ;

CMP_EQ  = '==' ;
CMP_NE  = '!=' ;
CMP_GT  = '>'  ;
CMP_LT  = '<'  ;
CMP_GE  = '>=' ;
CMP_LE  = '<=' ;
NULLISH = '??' ;
